# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4QjW3Pfc_nL8uJ4f_k3h_dBUx6n6k9g
"""

def load_balancing(tasks, num_machines=3):
    machines = [0] * num_machines
    assignment = [[] for _ in range(num_machines)]
    operations = 0

    for task in tasks:
        min_machine = min(range(num_machines), key=lambda i: machines[i])
        machines[min_machine] += task
        assignment[min_machine].append(task)
        operations += num_machines

    return machines, assignment, operations

tasks = [3, 5, 2, 7, 8, 4, 6]

machines, assignment, operations = load_balancing(tasks)

print("Tarefas:", tasks)
print("\nDistribuição das máquinas:")

for i in range(len(machines)):
    print(f"M{i+1} → {assignment[i]} (carga = {machines[i]})")

print("\nMakespan =", max(machines))
print("Operações realizadas =", operations)

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.bar(["M1", "M2", "M3"], machines)
plt.title("Carga das Máquinas (Experimento A)")
plt.ylabel("Tempo Total (s)")
plt.xlabel("Máquinas")
plt.show()

tasks_B = [10, 3, 7, 6, 12, 5, 4, 9]

machines_B, assignment_B, operations_B = load_balancing(tasks_B)

print("=== Experimento B ===")
print("Tarefas:", tasks_B)
print("\nDistribuição das máquinas:\n")

for i in range(len(machines_B)):
    print(f"M{i+1} → {assignment_B[i]} (carga = {machines_B[i]})")

print("\nMakespan =", max(machines_B))
print("Operações realizadas =", operations_B)

plt.figure(figsize=(6,4))
plt.bar(["M1", "M2", "M3"], machines_B)
plt.title("Carga das Máquinas (Experimento B)")
plt.ylabel("Tempo Total (s)")
plt.xlabel("Máquinas")
plt.show()

tasks_C = [5, 12, 3, 8, 7, 15, 9, 4, 11, 6, 14, 13]

machines_C, assignment_C, operations_C = load_balancing(tasks_C)

print("=== Experimento C ===")
print("Tarefas:", tasks_C)
print("\nDistribuição das máquinas:\n")

for i in range(len(machines_C)):
    print(f"M{i+1} → {assignment_C[i]} (carga = {machines_C[i]})")

print("\nMakespan =", max(machines_C))
print("Operações realizadas =", operations_C)

plt.figure(figsize=(6,4))
plt.bar(["M1", "M2", "M3"], machines_C)
plt.title("Carga das Máquinas (Experimento C)")
plt.ylabel("Tempo Total (s)")
plt.xlabel("Máquinas")
plt.show()